version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_tiktok_b24
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tiktok_b24
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_tiktok_b24
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
